name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build WAR
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t demo-app .

    - name: Stop old container
      run: docker stop demo || true

    - name: Remove old container
      run: docker rm demo || true

    - name: Run new container
      run: docker run -d -p 8080:8080 --name demo demo-app